---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openldap-clients
    - sssd
    - sssd-client
    - sssd-ldap
    - sssd-tools
    - authconfig
    - nss-pam-ldapd
    - oddjob-mkhomedir

- name: Add LDAP configuration lines to ldap.conf
  lineinfile:
    path: /etc/openldap/ldap.conf
    line: "{{ item }}"
  with_items:
    - "BASE   {{ ldap_server.dc }}"
    - "URI    ldap://{{ ldap_server_ip }}"