---
- name: Add line to PAM configuration for automatic home directory creation
  lineinfile:
    path: /etc/pam.d/sshd  # The path to the PAM configuration file
    line: "session    required     pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
    insertafter: 'session    optional     pam_selinux.so close'  # Insert after this line
  notify: Restart SSH Service

- name: Configure PAM for SSSD
  shell: "authconfig --enablesssdauth --update"
  register: result
  failed_when: false
  retries: 2
  delay: 3
  until: result is failed

- name: debug
  debug:
    msg: "{{ result }}"

- name: Copy SSSD service config
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600

- name: Set UsePAM to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?UsePAM'
    line: 'UsePAM yes'
    state: present
  notify: Restart SSH Service

- name: Set PasswordAuthentication to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
  notify: Restart SSH Service

- name: Start SSSD Service
  systemd:
    name: sssd
    state: restarted
    enabled: yes
