---
- name: Stopped System Service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - firewalld
    - NetworkManager

- name: Set Selinux to Disabled
  lineinfile:
    dest: '/etc/selinux/config'
    regexp: '^SELINUX=.*'
    line: 'SELINUX=disabled'
    state: present

- name: Set Kernel Parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
  with_items:
    - { name: "fs.file-max", value: "65536" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "8192" }
    - { name: "net.core.somaxconn", value: "65535" }
    - { name: "vm.swappiness", value: "10" }
    - { name: "vm.overcommit_memory", value: "0" }
    - { name: "vm.dirty_ratio", value: "10" }
    - { name: "vm.dirty_background_ratio", value: "5" }
    - { name: "vm.vfs_cache_pressure", value: "100" }
    - { name: "kernel.pid_max", value: "65536" }

- name: Set sshd config
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^UseDNS'
    line: 'UseDNS no'
    state: present
  notify: Restart SSH Service

- name: Add Hosts for openldap
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Set Time Zone to Asia/Shanghai
  copy:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime

- name: config pip
  copy:
    src: pip.conf
    dest: /etc/pip.conf

