---
- name: find repo files
  find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
  register: repo_files

- name: delete yum files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ repo_files.files }}"

- name: Ensure YUM Repository is present
  yum_repository:
    name: "{{ item.key }}"
    baseurl: "{{ item.value }}"
    enabled: yes
    gpgcheck: no
    description: ''
  with_dict: "{{ yum }}"

- name: install software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - chrony
    - net-tools
    - python-devel
    - gcc
    - openldap-devel


- name: copy chrony config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: startup chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes
