---
- name: Create OpenLDAP TOP
  ldap_entry:
    dn: "{{ ldap_server.dc }}"
    objectClass:
      - top
      - domain
    state: present
    server_uri: "ldap://{{ ldap_server_ip }}"
    bind_dn: "{{ ldap_server.admin.dn }}"
    bind_pw: "{{ ldap_user.admin.pass }}"

- name: Create OU
  ldap_entry:
    dn: "ou={{ item }},{{ ldap_server.dc }}"
    objectClass: organizationalUnit
    attributes:
      ou: "{{ item }}"
    state: present
    server_uri: "ldap://{{ ldap_server_ip }}"
    bind_dn: "{{ ldap_server.admin.dn }}"
    bind_pw: "{{ ldap_user.admin.pass }}"
  with_items:
    - groups
    - users
    - services
    - sudoers
    - pwpolicies